apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - binding:
        name: trigger-binding-pipeline
      template:
        name: trigger-template-pipeline
