apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-debug
      default: "0"
    - name: repository
      value: https://github.com/savya-alla/tekton-node-app
      description: the git repo
    - name: app-name
      value: tekton-test
      description: application name
    - name: source-dir
      value: "." 
    - name: task-pvc
      value: tekton-pvc
    - name: statuses-repo-url
      description: the base repository's status URL
      value: https://github.com/savya-alla/tekton-node-app
    - name: branch
      description: the branch for the git repo
      defualt: master
    - name: revision
      description: |
        the git revision/commit to update the git HEAD to.
        Default is to mean only use the branch
    - name: toolchain-branch
      default: master
      
  workspaces:
    - name: artifacts
    
  tasks:
    - name: clean-dir
      taskRef:
        name: task-clean-dir

    - name: tekton-build-tasks-github-status-pending
      taskRef:
        name: task-setgit-status
      params:
        - name: repo-url
          value: $(params.statuses-repo-url)
        - name: commit-sha
          value: $(params.revision)
        - name: state
          value: pending
        - name: task-name
          value: tekton-build-task
        - name: step-name
          value: tekton-build
        - name: description
          value: building the code...
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: tekton-build-task
      taskRef:
        name: task-build
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: source-dir
          value: $(params.repository)
        - name: app-name
          value: $(params.revision)
        - name: task-pvc
          value: tekton-pvc

    - name: tekton-build-tasks-github-status-result
      taskRef:
        name: github-set-status
      workspaces:
        - name: secrets
          workspace: artifacts
      params:
        - name: repo-url
          value: $(params.statuses-repo-url)
        - name: commit-sha
          value: $(params.revision)
        - name: state
          value: $(tasks.tekton-build-task.results.status)
        - name: task-name
          value: task-build-task
        - name: step-name
          value: tekton-build
        - name: description
          value: Running Tekton build...
        - name: pipeline-debug
          value: $(params.pipeline-debug)

