apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-debug
      default: "0"
    - name: repository
      default: https://github.com/savya-alla/tekton-node-app
      description: the git repo
    - name: app-name
      default: tekton-test
      description: application name
    - name: source-dir
      default: "." 
    - name: task-pvc
      default: tekton-pvc
    - name: statuses-repo-url
      description: the base repository's status URL
      default: https://github.com/savya-alla/tekton-node-app
    - name: branch
      description: the branch for the git repo
      default: master
    - name: revision
      description: |
        the git revision/commit to update the git HEAD to.
        Default is to mean only use the branch
      default: master
    - name: toolchain-branch
      default: master
    - name: secret-name
      default: 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
    
  workspaces:
    - name: secrets
    
  tasks:
    - name: tekton-build-tasks-github-status-pending
      taskRef:
        name: task-setgit-status
      workspaces:
        - name: secrets
          workspace: secrets
      params:
        - name: secret-name
          value: $(params.secret-name)
        - name: repo-url
          value: $(params.statuses-repo-url)
        - name: commit-sha
          value: $(params.revision)
        - name: state
          value: pending
        - name: task-name
          value: tekton-build-task
        - name: step-name
          value: tekton-build
        - name: description
          value: building the code...
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: tekton-build-task
      taskRef:
        name: task-build
      params:
        - name: app-name
          value: $(params.revision)
        - name: task-pvc
          value: tekton-pvc

    - name: tekton-build-tasks-github-status-result
      taskRef:
        name: task-setgit-status
      workspaces:
        - name: secrets
          workspace: secrets
      params:
        - name: secret-name
          value: $(params.secret-name)
        - name: repo-url
          value: $(params.statuses-repo-url)
        - name: commit-sha
          value: $(params.revision)
        - name: state
          value: $(tasks.tekton-build-task.results.status)
        - name: task-name
          value: tekton-build-task
        - name: step-name
          value: tekton-build
        - name: description
          value: Tekton build Completed...
        - name: pipeline-debug
          value: $(params.pipeline-debug)

