apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-build
spec:
  params:
      - name: app-name
        description: name of the application to buidl
      - name: task-pvc
        description: output pvc
        
  results:
    - name: exit-code
      description: The exit-code of the script
    - name: status
      description: The status based on exit-code
      
  steps:
    - name: build-setup
      image: ibmcom/pipeline-base-image
      command: ["/bin/bash", "-c"]
      env:
        - name: NPMRC
          valueFrom:
            secretKeyRef:
              name: tekton-secrets
              key: npmrc
      args:
        - set -e -o pipefail;
          apt-get update && apt-get install -y curl && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*;
          echo "cd to /artifacts/$(params.app-name)";
          cd /artifacts/$(params.app-name);
          echo "Copy .npmrc file to current /artifacts/$(params.app-name)";
          echo "${NPMRC}" >> .npmrc;
          cat .npmrc;
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
    - name: build-app
      image: bss-armada-docker-staging-local.artifactory.swg-devops.com/bss-jenkins-agent-image-node10:production
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "cd to /artifacts/$(params.app-name)";
          cd /artifacts/$(params.app-name);
          pwd;
          ls -al;
          echo "npm install";
          npm install;
          BUILD_FAIL=$?
          if [[ $BUILD_FAIL == 0 ]]; then
              echo "Build Complete, No Errors Found!"
              echo $BUILD_FAIL | tee $(results.exit-code.path)
              echo -n success | tee $(results.status.path)
          else
              echo "Build Failed"
              echo $BUILD_FAIL | tee $(results.exit-code.path)
              echo -n fail | tee $(results.status.path)
          fi
          ls -al;
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
  - name: task-volume
    persistentVolumeClaim:
      claimName: $(params.task-pvc)
