apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clean-dir
  namespace: tekton-test
spec:
  steps:
    - name: clean-dir
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          cd /artifacts;
          rm -rf *;
          echo "artifacts deleted successfully";
          ls -al;
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: tekton-pvc
